### ISSUE TITLE
Error: undefined method `delete' if the timesheet has invalid record

### ISSUE THREAD

**Issue by sEpt0r** [nixargh/sheetocan#11]
I received an error if the timesheet has invalid record instead of line number with the error.

```sheetocan:197:in `block in read': undefined method `delete' for nil:NilClass (NoMethodError)
	from /Users/sEpt0r/iponweb/sheetocan/sheetocan:175:in `each'
	from /Users/sEpt0r/iponweb/sheetocan/sheetocan:175:in `inject'
	from /Users/sEpt0r/iponweb/sheetocan/sheetocan:175:in `read'
	from /Users/sEpt0r/iponweb/sheetocan/sheetocan:100:in `report'
	from /Users/sEpt0r/iponweb/sheetocan/sheetocan:461:in `<main>'```

**Comment by nixargh** [comment]
Please try [2.3.1](https://github.com/nixargh/sheetocan/tree/2.3.1)

**Comment by sEpt0r** [comment]
It works, thanks.
