### ISSUE TITLE
Validate timesheet in process

### ISSUE THREAD

**Issue by paskal** [nixargh/sheetocan#3]
``` bash
➜  ~  tail -1 ~/iponweb/admin/timesheet/dverhoturov
2015-08-18,13:16,13:11,iowops,RT:999999,"some description"
➜  ~  iponweb/scripts/sheetocan/sheetocan.rb -m 8 -r
1.07, 10.3, 87.48 (168, -81)
➜  ~  cvs commit -m "" iponweb/admin/timesheet/dverhoturov
error: check-timesheet-syntax returned the following message:
CVS parse error at - (row 1873): Start time >= than end time

cvs commit: Pre-commit check failed
cvs [commit aborted]: correct above errors first!
```

Your tool could tell the same thing, that will be cool.

**Comment by nixargh** [comment]
Validation procedure added to report error in following cases:
- end time less or equal to start time
- start time less or equal to end time of previous line

Commit: [cf619cbb02ec0f2a3da35b7490f032408de91a6c](https://github.com/nixargh/sheetocan/commit/cf619cbb02ec0f2a3da35b7490f032408de91a6c)
