### ISSUE TITLE
Add an option for "time bubbles" in timesheet

### ISSUE THREAD

**Issue by paskal** [nixargh/sheetocan#5]
Please add an option which will show non-working time in current day between first and last time worked (e.g. catch launch break, for example).

**Comment by nixargh** [comment]
Dear paskal,
i added new option '-b' or '--bubbles'. Please check that it works as you expected.

Done at [commit](https://github.com/nixargh/sheetocan/commit/b1868be47d91ec978b4c0113b6981abc23c9234b).

**Comment by paskal** [comment]
Awesome, thanks! Could you please make it ignore bubbles for provided amount of hours, like -b 4 means 4h? This size bubble you'll see yourself for sure, and it's often normal because you can work some time at night (duty call;) and don't want to see bubble with 9h in the morning.

**Comment by nixargh** [comment]
Done.
Now you could set float value (hours) for -b. By default it equals to 24.

**Comment by nixargh** [comment]
I removed default for -b because it doesn't work.

**Comment by paskal** [comment]
It's working for me as expected:
➜  ~  sheetocan/sheetocan.rb -m 9 -b 3 -r ~/**
7.38, 36.85, 77.43 (176, -99) [0.0]
➜  ~  sheetocan/sheetocan.rb -m 9 -b 5 -r ~/**
7.38, 36.85, 77.43 (176, -99) [4.2]
Default should be like 4 hours by my opinion (difference between late night and day work).

**Comment by nixargh** [comment]
I decided not to do default for --bubbles option because every person has his own time out during work day.
