### ISSUE TITLE
Option -m shows time for current year

### ISSUE THREAD

**Issue by sEpt0r** [nixargh/sheetocan#9]
Could you change behaviour for option -m if current month less than specified?
For example:
```
./sheetocan -r -m 1 ~/timesheet/name
3.88, 3.88, 4.8 (136, -132)

./sheetocan -r -m 12 ~/timesheet/name
0.0, 0.0, 0.0 (168, -168)
```
The latest command shows Dec 2017 instead Dec 2016.

**Comment by nixargh** [comment]
Fixed at [2.1.1](https://github.com/nixargh/sheetocan/releases/tag/2.1.1)
